### ISSUE TITLE
display output URL instead of goto

### ISSUE THREAD

**Issue by kjhiller** [uclibs/proxy_user#4]
On the admin page http://libapps.libraries.uc.edu/proxyuser/admin.html can you please change the function of "URL to SPU" so that it displays the output URL instead of automatically going to the URL?  thanks

**Comment by scherztc** [comment]
Add another button that would allow the echo of the URL Re-writer to echo out the starting point URL with the prefix.  GoTo Page or Copy Link.

**Comment by scherztc** [comment]
https://guides.libraries.uc.edu/c.php?g=1042067

**Comment by scherztc** [comment]
Fixed with latest commit.
